#!/usr/bin/env python3
"""Stage only the website and its local dependencies; never copy a source tree wholesale."""
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit, unquote
import hashlib
import json
import shutil
import tempfile

ROOT = Path(__file__).resolve().parents[1]
ENTRYPOINTS = ['index.html', 'research.html', 'members.html', 'publications.html', 'gallery.html', 'contact.html']


class References(HTMLParser):
    def __init__(self):
        super().__init__()
        self.paths = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        for key in ('href', 'src'):
            value = attrs.get(key, '')
            url = urlsplit(value)
            if url.scheme or url.netloc or not url.path:
                continue
            self.paths.append(unquote(url.path))


def public_files():
    pending = [Path(p) for p in ENTRYPOINTS]
    found = set()
    while pending:
        path = pending.pop()
        if path in found:
            continue
        if path.is_absolute() or '..' in path.parts:
            raise ValueError('Unsafe public path: ' + str(path))
        allowed = (str(path) in ENTRYPOINTS
                   or (path.parts[0] in ('images', 'css', 'js') and path.suffix in ('.png', '.jpg', '.webp', '.css', '.js')))
        if not allowed:
            raise ValueError('File outside public allowlist: ' + str(path))
        source = ROOT / path
        if not source.is_file() or source.is_symlink():
            raise ValueError('Missing file or symlink: ' + str(path))
        found.add(path)
        if path.suffix == '.html':
            parser = References()
            parser.feed(source.read_text())
            pending.extend(path.parent / p for p in parser.paths)
    return sorted(found)


def main():
    files = public_files()
    # Construct the whole package first. Only our generated dist folder is replaced.
    with tempfile.TemporaryDirectory(prefix='gnugpl-publish-') as directory:
        staged = Path(directory) / 'dist'
        staged.mkdir()
        manifest = []
        for path in files:
            target = staged / path
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / path, target)
            manifest.append({'path': str(path), 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()})
        (staged / '.nojekyll').write_text('')
        (staged / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
        destination = ROOT / 'dist'
        if destination.exists():
            # This marker prevents deletion of an unrelated user directory.
            if not (destination / 'manifest.json').is_file() or not (destination / '.nojekyll').is_file():
                raise ValueError('Existing dist/ was not generated by this script.')
            shutil.rmtree(destination)
        shutil.copytree(staged, destination)
    print(f'Packaged {len(files)} public files in dist/; PDFs and raw/manuscripts/workshop/source files excluded.')


if __name__ == '__main__':
    main()
